### PR TITLE
Added rounding mode param to divide method

### PR DESCRIPTION
**Pull request by Sword-of-GraySkull**
Since the divide method lacks the rounding mode parameter, this [line](https://github.com/royNiladri/js-big-decimal/blob/5a47b163b831b588cdc912ede54ef83c61bbb2d3/src/divide.ts#L93) defaults the rounding to (HALF EVEN)

Hence,  adding the rounding mode param to round the result of divide method to be rounded with other rounding options

### CODE REVIEW

**Review by Jsoto22 — APPROVED** [review]
Good enhancement, simple implementation, and includes UT.

**Comment by Sword-of-GraySkull** [comment]
@Jsoto22 Can you please rerun the workflows?

**Comment by Sword-of-GraySkull** [comment]
@Jsoto22  

[npm-publish job](https://github.com/royNiladri/js-big-decimal/actions/runs/9656496929/job/26634118542) seems to have not published the package. Because is_version is returned as false in the 'Check if tag is a version' step. Could you please assist?

**Comment by Jsoto22** [comment]
I'm currently looking into a few things I noticed come up in the workflow. I'll get back to you when I can.

**Comment by Sword-of-GraySkull** [comment]
@Jsoto22  @royNiladri 

Have you been able to look up the [npm-publish](https://github.com/royNiladri/js-big-decimal/actions/runs/9656496929/job/26634118542) job failure?

I can see that you are looking for any difference between the last published npm version and the latest git tag for the publish step to happen. But, I couldn't figure out when the new tag was created.

**Comment by Jsoto22** [comment]
Sorry, haven't had much time since. I'll prep a release to create the missing tag tomorrow if I can.

**Comment by Sword-of-GraySkull** [comment]
Hey @Jsoto22 , I understand you're likely busy. But I wanted to follow up on the release request.

**Comment by royNiladri** [comment]
Sorry all, have been realy busy on the family front of things, and have not
been able to respond for quite a while. We need to bump the version
manually (npm version patch/minor/major) based on what type of changes.. if
there are a lot of new changes coming in, even though no old use case is
impacted, still make it a major version. Otherwise go with minor.

**Comment by Sword-of-GraySkull** [comment]
Thanks, @royNiladri for the update. I have manually updated the version from 2.0.7 to 2.0.8 in [package.json](https://github.com/royNiladri/js-big-decimal/pull/135/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R3). So, I believe we shouldn't bump the version with `npm version minor` again. Can you create a tag for `2.0.8` and publish it for now?

**Comment by Sword-of-GraySkull** [comment]
@royNiladri 

As mentioned, Could you create a tag for 2.0.8 and publish the version?

**Comment by royNiladri** [comment]
Hi all,
Sorry for the delayed response. I have updated the readme, and published a
minor version update!
[image: image.png]

Cheer🥳

**Comment by royNiladri** [comment]
Hi @Sword-of-GraySkull & @Jsoto22,
Sorry for the delayed response. I have updated the Readme, and published a
minor version update! v2.1.0
image

Cheer🥳

**Pull request merged**
